#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
  echo "This command must be executed as root or with sudo."
  exit 1
fi

printf "Entering Homebridge Shell. To exit type 'exit'.\n\n"

cd "/var/lib/homebridge"

exec sudo --user homebridge bash --rcfile /opt/homebridge/bashrc-hb-shell
