#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
  echo "This command must be executed as root or with sudo."
  exit 1
fi

# change to working directory
cd "/var/lib/homebridge"

# default shell user
SHELL_USER=homebridge

# if a systemd override is in place, check which user the shell should run as
if [ -f /etc/systemd/system/homebridge.service.d/override.conf ]; then
  OVERRIDE_USER=$(cat /etc/systemd/system/homebridge.service.d/override.conf | grep '^[[:blank:]]*[^[:blank:]#;]' | awk /User=/ | awk -F "=" '{print $2}' | xargs)
  if [ ${#OVERRIDE_USER} -gt 0 ]; then
    # check if user exists
    getent passwd $OVERRIDE_USER > /dev/null
    if [ "$?" -eq 0 ]; then
      SHELL_USER=$(id -nu $OVERRIDE_USER)
      echo "User: $SHELL_USER (/etc/systemd/system/homebridge.service.d/override.conf)"
    else
      echo "ERROR: User '$OVERRIDE_USER' as defined in /etc/systemd/system/homebridge.service.d/override.conf does not exist on the system!"
    fi
  fi
fi

# get the shell user's home directory
SHELL_USER_HOME=$(eval echo ~$SHELL_USER)

printf "Entering Homebridge Shell. To exit type 'exit'.\n\n"

exec sudo --user "$SHELL_USER" env "HOME=$SHELL_USER_HOME" bash --rcfile /opt/homebridge/bashrc-hb-shell
