#!/bin/sh

# Ensure the storage path permissions are correct
if [ -n "$USER" ] && [ "$USER" != "root" ]; then
  echo "Ensuring /var/lib/homebridge and /opt/homebridge are owned by $USER"
  [ -d /var/lib/homebridge ] || mkdir -p /var/lib/homebridge
  chown -R $USER: /var/lib/homebridge /opt/homebridge
fi
