#!/bin/bash

# post-upgrade only
if [ "$1" = "configure" ] && [ $2 ]; then
  echo "Running post-upgrade steps..."

  # stop homebridge.service if it is running
  if systemctl is-active --quiet homebridge.service; then
    echo "Stopping Homebridge service..."
    systemctl stop homebridge.service 2> /dev/null
  fi

  # merge old package.json with new one:
  if [ -f /tmp/homebridge-tmp/package.json ] && [ -f /var/lib/homebridge/package.json ]; then
    echo "Merging package.json file..."

    # enter homebridge env
    . "/opt/homebridge/source.sh"

    # merge the new package.json into the old one, and save
    PACKAGE_JSON=$(jq -M -s '.[0] * .[1]' /tmp/homebridge-tmp/package.json /var/lib/homebridge/package.json) > /var/lib/homebridge/package.json
    if [ "$?" = "0" ]; then
      echo $PACKAGE_JSON | jq '.' > /var/lib/homebridge/package.json
    fi

    # Re-install user plugins
    echo "Re-installing user plugins, this may take a few minutes, please wait..."
    pnpm -C /var/lib/homebridge install

    # remove tmp package.json
    rm -rf /tmp/homebridge-tmp/package.json
  fi
fi

# post-install and post-upgrade
if [ "$1" = "configure" ]; then
  echo "Running post-install steps..."

  # create user
  adduser --system homebridge 2> /dev/null

  # copy .bashrc to service user home
  cp /opt/homebridge/bashrc /home/homebridge/.bashrc

  # fix permissions on homebridge user home
  chown -R homebridge: /home/homebridge/.bashrc

  # clear any masks on the homebridge service
  systemctl unmask homebridge.service 2> /dev/null

  # reload systemctl
  systemctl daemon-reload

  # enable systemctl service
  systemctl enable homebridge.service

  # start / restart homebridge
  echo "Starting Homebridge service...."
  systemctl restart homebridge.service

  # create symlink to hb-shell
  ln -fs /opt/homebridge/hb-shell /usr/local/bin/hb-shell

  # add user to default groups if running on raspbian
  . /etc/os-release
  if [ "$ID" = "raspbian" ]; then
    for groupName in udio bluetooth dialout gpio video input i2c spi audio render; do
      usermod -a -G $groupName homebridge 2> /dev/null
    done
  fi
fi

# post-install only
if [ "$1" = "configure" ] && [ -z $2 ]; then
  IP=$(hostname -I)
  PORT=8581

  # check to see if an alternate port is defined in the config
  if [ -f /var/lib/homebridge/config.json ]; then
    PORT_FROM_CONFIG=$(cat /var/lib/homebridge/config.json | jq '.platforms[] | select(.platform | contains("config")) | .port' 2> /dev/null)
    if [ ${#PORT_FROM_CONFIG} -gt 0 ]; then
      PORT=$PORT_FROM_CONFIG
    fi
  fi

  echo ""
  echo "Homebridge Installation Complete!"
  echo "You can access the Homebridge UI via:"
  echo ""

  for ip in $IP; do
    if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      echo "* http://$ip:$PORT"
    else
      echo "* http://[$ip]:$PORT"
    fi
  done

  echo ""
  echo "Thanks for installing Homebridge!"
  echo ""
fi

exit 0