#!/bin/bash

# before install
if [ "$1" = "install" ]; then
  echo "Running pre-install steps..."

  # check for existing homebridge.service 
  if [ -f /etc/systemd/system/homebridge.service ]; then
    # stop homebridge.service if it is running
    if systemctl is-active --quiet homebridge.service; then
      echo "Stopping existing Homebridge service..."
      systemctl stop homebridge.service
    fi

    # disable and remove the old homebridge.service
    echo "Removing existing Homebridge service..."
    systemctl disable homebridge.service
    rm -rf /etc/systemd/system/homebridge.service
    systemctl daemon-reload
  fi

  # remove the hb-service generated fix-permission pre-start script
  if [ -f /etc/hb-service/homebridge/prestart.d/10-fix-permissions ]; then
    rm -rf /etc/hb-service/homebridge/prestart.d/10-fix-permissions
  fi
fi

# before an upgrade
if [ "$1" = "upgrade" ] && [ $2 ]; then
  echo "Running pre-upgrade steps..."

  # stop homebridge.service if it is running
  if systemctl is-active --quiet homebridge.service; then
    echo "Stopping Homebridge service..."
    systemctl stop homebridge.service 2> /dev/null
  fi

  # take a copy of the existing "package.json"
  mkdir -p /tmp/homebridge-tmp
  [ -f /var/lib/homebridge/package.json ] && cp /var/lib/homebridge/package.json /tmp/homebridge-tmp/package.json

  # remove existing node_modules and lock files
  # the postinst upgrade step will merge the new package.json with the existing one
  # user plugins are re-installed during the postinst upgrade step
  rm -rf /var/lib/homebridge/node_modules
  rm -rf /var/lib/homebridge/pnpm-lock.yaml
  rm -rf /var/lib/homebridge/package.json
fi

exit 0
