name: Alpha Stage 1 - Update Alpha Dependencies, Create PR, Merge PR and Trigger Alpha Stage 2
on:
  schedule:
    - cron: '0 9 * * *' # 5 AM Eastern (11 AM UTC), Docker updates at 6 AM Eastern (12 PM UTC)
  workflow_dispatch:
run-name: Alpha Stage 1 - ${{ github.event_name == 'workflow_dispatch' && 'Manual' || 'Scheduled' }} Run

jobs:
  update_dependencies:
    uses: ./.github/workflows/reusable-update-dependencies.yml
    with:
      release_type: alpha
      config_file: '.github/homebridge-alpha-bot.json'
      trigger_workflow: 'alpha-stage-2_build_alpha_release_and_store.yml'
    secrets: inherit