name: Beta Stage 1 - Update Beta Dependencies, Create PR, Merge PR and Trigger Beta Stage 2
on:
  schedule:
    - cron: '0 8 * * *' # 4 AM Eastern (10 AM UTC), Docker updates at 6 AM Eastern (12 PM UTC)
  workflow_dispatch:
run-name: Beta Stage 1 - ${{ github.event_name == 'workflow_dispatch' && 'Manual' || 'Scheduled' }} Run

jobs:
  update_dependencies:
    uses: ./.github/workflows/reusable-update-dependencies.yml
    with:
      release_type: beta
      config_file: '.github/homebridge-beta-bot.json'
      trigger_workflow: 'beta-stage-2_build_beta_release_and_store.yml'
    secrets: inherit