name: Beta Stage 2 - Build and Release Beta Package

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  build_and_release:
    uses: ./.github/workflows/reusable-build-and-release-prerelease.yml
    with:
      release_type: beta
      event_name: ${{ github.event_name }}
      pr_merged: ${{ github.event.pull_request.merged }}
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}