name: "Reusable - Publish to NPM"

on:
  workflow_call:
    inputs:
      npm_version:
        description: 'NPM version string'
        required: true
        type: string
      npm_tag:
        description: 'NPM tag (latest, beta, alpha)'
        required: false
        type: string
        default: 'latest'
      package_name:
        description: 'NPM package name'
        required: false
        type: string
        default: '@homebridge/homebridge-apt-pkg'
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish_to_npm:
    name: NPM Publish ${{ inputs.npm_version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: 'https://registry.npmjs.org'

      - name: Set package.json version
        run: |
          NPM_VERSION="${{ inputs.npm_version }}"
          echo "Setting version to $NPM_VERSION"
          jq ".version = \"$NPM_VERSION\"" package.json > tmp.$$.json && mv tmp.$$.json package.json
          cat package.json

      - name: Publish to npm
        run: npm publish --access public --tag ${{ inputs.npm_tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Output Success Notice
        run: echo "::notice::Published ${{ inputs.package_name }} as version ${{ inputs.npm_version }} with ${{ inputs.npm_tag }} tag"