name: "Reusable - Generate Version"

on:
  workflow_call:
    inputs:
      release_type:
        description: 'Release type (beta, alpha)'
        required: true
        type: string
      increment:
        description: 'Version increment type'
        required: false
        type: string
        default: 'patch'
    outputs:
      version:
        description: 'APT package version'
        value: ${{ jobs.generate_version.outputs.version }}
      npm_version:
        description: 'NPM version'
        value: ${{ jobs.generate_version.outputs.npm_version }}

jobs:
  generate_version:
    name: Generate ${{ inputs.release_type }} Package Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_output.outputs.version }}
      npm_version: ${{ steps.version_output.outputs.npm_version }}
    steps:
      - uses: actions/checkout@v4

      - name: Get base version
        uses: reecetech/version-increment@2023.10.1
        id: release_version
        with:
          scheme: semver
          increment: ${{ inputs.increment }}

      - name: Generate version
        id: version_output
        run: |
          BASE_VERSION=${{ steps.release_version.outputs.version }}
          BASE_VERSION_CLEAN=$(echo "$BASE_VERSION" | sed -E 's/-[a-z0-9.]+//')
          DATE=$(date +%Y%m%d)
          VERSION="${BASE_VERSION_CLEAN}~${{ inputs.release_type }}.${DATE}"
          NPM_VERSION="${BASE_VERSION_CLEAN}-${{ inputs.release_type }}.${DATE}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "npm_version=$NPM_VERSION" >> $GITHUB_OUTPUT
          echo "::notice::📦 ${{ inputs.release_type }} version: $VERSION"